server:
  port: 9527

spring:
  application:
    name: GateWay-Service
  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
      routes:
        # 路由的 ID，没有固定规则但要求唯一，建议配合服务名
        - id: payment-route1
        # 匹配后提供服务的路由地址
        # uri: http://localhost:8001 不能写死
        # 匹配 服务端 的路由地址，就是微服务名
          uri: lb://provider-payment-service
        # 断言，路径相匹配的进行路由
        # 配置服务端的方法路径
          predicates:
            - Path=/payment/lb/**

        - id: payment-route2
          uri: lb://provider-payment-service
          predicates:
            - Path=/payment/query/**


# Eureka
eureka:
  client:
    # 表示是否将自己注册到 EurekaServer
    register-with-eureka: true
    # 是否从 EurekaServer 抓取已有的注册信息
    # 单节点无所谓，集群必须设置为 true 才能配合 ribbon 使用
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka

  instance:
    hostname: GateWay-Service
