server:
  port: 8401
spring:
  application:
    name: sentinel-server
  cloud:
    nacos:
      discovery:
        # nacos 配置中心地址
        server-addr: localhost:8848
    sentinel:
      transport:
        # sentinel dashboard地址
        dashboard: localhost:8080
        # 默认端口 8719 假如被占用则会从 8719 开始依次扫描递增，直到找到未占用的端口
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*'
