server:
  port: 8006

# 服务别名
spring:
  application:
    name: provider-payment-service
  cloud:
    # 设置 consul 为注册中心
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&charaterEncoding=utf-8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource

# 整合 mybatis
mybatis:
  type-aliases-package: com.he.entities
  mapper-locations: classpath:mapper/*.xml



